### ISSUE TITLE
Is it possible to relicense this library to the Artistic License?

### ISSUE THREAD

**Issue by RyanBram** [sezero/libtimidity#1]
Hi, Sezero.
Currently there are 6 software known as MIDI Synthesizer, such as:

1. FluidSynth and its variants (LGPL);
2. WildMidi (LGPL);
3. Timidity++ (GPL);
4. BassMIDI (Closed Source);
5. SynthFont (Closed Source);
6. Platform specific synthesizer (Closed Source).

As you can see above, 3 of them is closed source and 3 of them is copyleft. Currently there is no choice for me who prefer non-copyleft license, such as Apache, BSD, Zlib, or MIT license.

Someday in the future, I plan to create my own game engine.  I did some investigation over the internet and most of the component from the scripting engine until media decoder have implementation in non-copyleft license, such as libxmp-lite for module player, stb_vorbis for audio, and so on. The only thing left is MIDI capability.

So if you want to relicense your improvement in this libtimidity to non copyleft license, it surely really helpful for me.

Thanks.

**Comment by sezero** [comment]
I forwarded your request to original author of libtimidity to have
his opinion on the matter.

**Comment by sezero** [comment]
It is done:  I allowed using libtimidity under Perl Artistic License, as well as GNU LGPL:
See the latest git master.  I will also release a 0.2.5 version today with this change.

Closing this issue.

**Comment by sezero** [comment]
And just released an official 0.2.5 version, download here:
http://sourceforge.net/project/downloading.php?group_id=124847&filename=libtimidity-0.2.5.tar.gz

**Comment by RyanBram** [comment]
I just want to drop by and say thank you very much for your permission.  (^_^)

**Comment by sezero** [comment]
> I just want to drop by and say thank you very much for your permission. (^_^)

You are welcome.
